/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik.view;

import Adapter.Adapter;
import Connection.ConnectionManager;
import Controller.Execute;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import klinik.view.MainView;
import Model.Pasien;
import Model.Pemeriksaan;
import Model.Resep;
import Model.Resep_Item;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author ASUS
 */
public class DokterView extends javax.swing.JFrame {
    String mencoba;
    public String id_pegawai,id_resep,rightnow;
    /**
     * Creates new form HomeView
     */
    public DokterView(String input){
        initComponents();
        displayAll();
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        buttonHome.setCursor(cursor);
        buttonPeriksa.setCursor(cursor);
        buttonKasir.setCursor(cursor);
        buttonObat.setCursor(cursor);
        buttonLogout.setCursor(cursor);
        
        mencoba = input;
         
    }

    private DokterView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void displayAll(){
        Adapter ag = new Adapter();
        Object[][] mypsn = ag.getPasienBlmPeriksa();
        tabellistpasien.setModel(new javax.swing.table.DefaultTableModel(
            mypsn,
            new String [] {
                "Nama", "Alamat ", "Tanggal Lahir"
            }
        ));
        jScrollPane1.setViewportView(tabellistpasien);
        
        Object[][] myrsp = ag.getResepStripProses();
        tabelpemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
           myrsp,
            new String [] {
                "ID Resep", "ID Pemeriksaan"
            }
        ));
        jScrollPane2.setViewportView(tabelpemeriksaan);
       
        Object[][] mypbyr = ag.getResepBlmProses();
        tabelpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            mypbyr,
            new String [] {
                "ID Resep", "ID Pemeriksaan"
            }
        ));
        jScrollPane4.setViewportView(tabelpembayaran); 
            
    }

    private String CekID_Obat(String obat){
        String sql = "Select * from obat where nama ='"+obat+"'";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.Logon();
        String Respon = null;
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                Respon = rs.getString("id_obat");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
        return Respon;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        periksa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnamapasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellistpasien = new javax.swing.JTable();
        prosesPeriksa = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        penyakit = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cbtramadol = new javax.swing.JCheckBox();
        cbpenisilin = new javax.swing.JCheckBox();
        cbparacetamol = new javax.swing.JCheckBox();
        cbasammefenamat = new javax.swing.JCheckBox();
        cbrhinos = new javax.swing.JCheckBox();
        cbbetadine = new javax.swing.JCheckBox();
        cbdeksametason = new javax.swing.JCheckBox();
        cbardium = new javax.swing.JCheckBox();
        cbcetirizine = new javax.swing.JCheckBox();
        cbesperson = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txttanggallahir = new javax.swing.JTextField();
        kasir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelpembayaran = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        idresephasil = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        idpemeriksaanhasil = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        namapasienhasil = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tanggalhasil = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tanggallahirhasil = new javax.swing.JTextField();
        namadokterhasil = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        totalhasil = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        obat = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpemeriksaan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabellistobat = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        labelboong2 = new javax.swing.JLabel();
        bayarbutton = new javax.swing.JButton();
        denied = new javax.swing.JPanel();
        SidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnamapekerja = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonPeriksa = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonKasir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonObat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/clinic.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/unilever.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/wingsfood.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/topbrand.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/indonesia.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel23.setText("Healthy With");

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel24.setText("The first modern clinic for in Indonesia");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(7, 7, 7))
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel23))
                            .addComponent(jLabel19)))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel24))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel22)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(77, 77, 77)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel21))
                        .addGap(11, 11, 11)))
                .addGap(23, 23, 23))
        );

        bodyPanel.add(home, "card2");

        periksa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 58)); // NOI18N
        jLabel6.setText("Diagnosis");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Nama :");

        txtnamapasien.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        tabellistpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellistpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellistpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellistpasien);

        prosesPeriksa.setText("PROSES");
        prosesPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesPeriksaActionPerformed(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(new java.awt.CardLayout());

        penyakit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel26.setText("List Obat");

        cbtramadol.setText("Tramadol");

        cbpenisilin.setText("Penisilin");

        cbparacetamol.setText("Paracetamol");

        cbasammefenamat.setText("Asam Mefenamat");

        cbrhinos.setText("Rhinos");

        cbbetadine.setText("Betadine");

        cbdeksametason.setText("Deksametason");

        cbardium.setText("Ardium");

        cbcetirizine.setText("Cetirizine");

        cbesperson.setText("Esperson");

        javax.swing.GroupLayout penyakitLayout = new javax.swing.GroupLayout(penyakit);
        penyakit.setLayout(penyakitLayout);
        penyakitLayout.setHorizontalGroup(
            penyakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penyakitLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(penyakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbesperson)
                    .addComponent(cbcetirizine)
                    .addComponent(cbardium)
                    .addComponent(cbdeksametason)
                    .addComponent(cbbetadine)
                    .addComponent(cbrhinos)
                    .addComponent(cbasammefenamat)
                    .addComponent(cbparacetamol)
                    .addComponent(cbpenisilin)
                    .addComponent(cbtramadol)
                    .addComponent(jLabel26))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        penyakitLayout.setVerticalGroup(
            penyakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penyakitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbtramadol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbpenisilin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbparacetamol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbasammefenamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbrhinos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbetadine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbdeksametason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbardium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbcetirizine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbesperson)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        menuPanel.add(penyakit, "card2");

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel25.setText("Alamat :");

        txtalamat.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel27.setText("TL :");

        txttanggallahir.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        javax.swing.GroupLayout periksaLayout = new javax.swing.GroupLayout(periksa);
        periksa.setLayout(periksaLayout);
        periksaLayout.setHorizontalGroup(
            periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periksaLayout.createSequentialGroup()
                .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(periksaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6))
                    .addGroup(periksaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(periksaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel25))
                            .addGroup(periksaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(periksaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttanggallahir, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnamapasien)
                                .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(periksaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(prosesPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        periksaLayout.setVerticalGroup(
            periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periksaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(periksaLayout.createSequentialGroup()
                        .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(prosesPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        bodyPanel.add(periksa, "card3");

        kasir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setText("Pembayaran");

        tabelpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpembayaranMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelpembayaran);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/clinickecilbeud.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel31.setText("Jl.Jurang No 704 B / 181, Kota Bandung");

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel32.setText("022-20391402");

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("=================================================================================");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel34.setText("ID Resep :");

        idresephasil.setEditable(false);
        idresephasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        idresephasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel35.setText("ID Pemeriksaan :");

        idpemeriksaanhasil.setEditable(false);
        idpemeriksaanhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        idpemeriksaanhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel36.setText("Nama Pasien :");

        namapasienhasil.setEditable(false);
        namapasienhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        namapasienhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelobat);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel37.setText("Obat :");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel38.setText("Tanggal : ");

        tanggalhasil.setEditable(false);
        tanggalhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tanggalhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel39.setText("Tanggal Lahir :");

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel40.setText("Nama Dokter :");

        tanggallahirhasil.setEditable(false);
        tanggallahirhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tanggallahirhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        namadokterhasil.setEditable(false);
        namadokterhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        namadokterhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("--------------------------------------------------------------------------------------------------------------------(+)");

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel42.setText("Total :");

        totalhasil.setEditable(false);
        totalhasil.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        totalhasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel43.setText("Terima kasih atas Kunjungan Anda");

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel44.setText("Semoga anda lekas sembuh ");

        jButton1.setText("PRINT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kasirLayout = new javax.swing.GroupLayout(kasir);
        kasir.setLayout(kasirLayout);
        kasirLayout.setHorizontalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirLayout.createSequentialGroup()
                                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kasirLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel30))
                                    .addComponent(jLabel31)
                                    .addGroup(kasirLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel32)))
                                .addGap(340, 340, 340))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirLayout.createSequentialGroup()
                                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addGap(12, 12, 12)))
                                .addGap(344, 344, 344))))
                    .addGroup(kasirLayout.createSequentialGroup()
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kasirLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel37)
                                        .addComponent(jScrollPane5)
                                        .addGroup(kasirLayout.createSequentialGroup()
                                            .addComponent(jLabel38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tanggalhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel42)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(totalhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel41))
                                    .addGroup(kasirLayout.createSequentialGroup()
                                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(kasirLayout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idresephasil))
                                            .addGroup(kasirLayout.createSequentialGroup()
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(idpemeriksaanhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kasirLayout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(namapasienhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(kasirLayout.createSequentialGroup()
                                                .addComponent(jLabel40)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(namadokterhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kasirLayout.createSequentialGroup()
                                                .addComponent(jLabel39)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tanggallahirhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(kasirLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(100, Short.MAX_VALUE))))
        );
        kasirLayout.setVerticalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasirLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(idresephasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(namadokterhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(idpemeriksaanhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(namapasienhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(tanggallahirhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(tanggalhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(totalhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44))
                    .addGroup(kasirLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        bodyPanel.add(kasir, "card4");

        obat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel17.setText("Obat");

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel28.setText("List Obat");

        tabelpemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpemeriksaanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpemeriksaan);

        tabellistobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellistobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellistobatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabellistobat);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel29.setText("Resep");

        labelboong2.setBackground(new java.awt.Color(255, 255, 255));
        labelboong2.setForeground(new java.awt.Color(255, 255, 255));
        labelboong2.setText("labelboong2");

        bayarbutton.setText("Pembayaran");
        bayarbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout obatLayout = new javax.swing.GroupLayout(obat);
        obat.setLayout(obatLayout);
        obatLayout.setHorizontalGroup(
            obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(obatLayout.createSequentialGroup()
                        .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelboong2)
                            .addComponent(jLabel17))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(obatLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
            .addGroup(obatLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(bayarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(obatLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel29)
                    .addContainerGap(952, Short.MAX_VALUE)))
        );
        obatLayout.setVerticalGroup(
            obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatLayout.createSequentialGroup()
                .addComponent(labelboong2)
                .addGap(7, 7, 7)
                .addComponent(jLabel17)
                .addGap(37, 37, 37)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(bayarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(obatLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel29)
                    .addContainerGap(575, Short.MAX_VALUE)))
        );

        bodyPanel.add(obat, "card5");

        javax.swing.GroupLayout deniedLayout = new javax.swing.GroupLayout(denied);
        denied.setLayout(deniedLayout);
        deniedLayout.setHorizontalGroup(
            deniedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        deniedLayout.setVerticalGroup(
            deniedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        bodyPanel.add(denied, "card6");

        SidebarPanel.setBackground(new java.awt.Color(179, 47, 51));
        SidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/logohatikecil.png"))); // NOI18N
        SidebarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        txtnamapekerja.setBackground(new java.awt.Color(255, 255, 255));
        txtnamapekerja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnamapekerja.setForeground(new java.awt.Color(255, 255, 255));
        txtnamapekerja.setText("Muhamad Haikal");
        SidebarPanel.add(txtnamapekerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat datang, selamat bekerja");
        SidebarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        buttonLogout.setBackground(new java.awt.Color(179, 47, 51));
        buttonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogoutMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Keluar");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/logout.png"))); // NOI18N

        javax.swing.GroupLayout buttonLogoutLayout = new javax.swing.GroupLayout(buttonLogout);
        buttonLogout.setLayout(buttonLogoutLayout);
        buttonLogoutLayout.setHorizontalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        buttonLogoutLayout.setVerticalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(buttonLogoutLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        SidebarPanel.add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 230, 50));

        buttonHome.setBackground(new java.awt.Color(230, 56, 62));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/home.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Home");

        javax.swing.GroupLayout buttonHomeLayout = new javax.swing.GroupLayout(buttonHome);
        buttonHome.setLayout(buttonHomeLayout);
        buttonHomeLayout.setHorizontalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        buttonHomeLayout.setVerticalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 60));

        buttonPeriksa.setBackground(new java.awt.Color(179, 47, 51));
        buttonPeriksa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPeriksaMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/dokter.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Periksa");

        javax.swing.GroupLayout buttonPeriksaLayout = new javax.swing.GroupLayout(buttonPeriksa);
        buttonPeriksa.setLayout(buttonPeriksaLayout);
        buttonPeriksaLayout.setHorizontalGroup(
            buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPeriksaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        buttonPeriksaLayout.setVerticalGroup(
            buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPeriksaLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15))
        );

        SidebarPanel.add(buttonPeriksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 60));

        buttonKasir.setBackground(new java.awt.Color(179, 47, 51));
        buttonKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKasirMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kasir");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/kasir.png"))); // NOI18N

        javax.swing.GroupLayout buttonKasirLayout = new javax.swing.GroupLayout(buttonKasir);
        buttonKasir.setLayout(buttonKasirLayout);
        buttonKasirLayout.setHorizontalGroup(
            buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonKasirLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        buttonKasirLayout.setVerticalGroup(
            buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(buttonKasirLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        buttonObat.setBackground(new java.awt.Color(179, 47, 51));
        buttonObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonObatMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Obat");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/obat.png"))); // NOI18N

        javax.swing.GroupLayout buttonObatLayout = new javax.swing.GroupLayout(buttonObat);
        buttonObat.setLayout(buttonObatLayout);
        buttonObatLayout.setHorizontalGroup(
            buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonObatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        buttonObatLayout.setVerticalGroup(
            buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonObatLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/line.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        SidebarPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(home);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(230, 56, 62));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(179, 47, 51));
       
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonPeriksaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPeriksaMouseClicked
//        String sql = "Select * from login where username = '" + txtusername.getText() + "' and password= '" + txtpassword.getText() + "'";
//        ConnectionManager conMan = new ConnectionManager();
//        Connection conn = conMan.Logon();
//        try {
//            Statement stm = conn.createStatement();
//            ResultSet rs = stm.executeQuery(sql);
//            if (rs.next()) {
//                if (txtusername.getText().equals(rs.getString("username")) && txtpassword.getText().equals(rs.getString("password"))) {
//                    JOptionPane.showMessageDialog(null, "BERHASIL !!!");
//                    DokterView dv = new DokterView(rs.getString("username"));
//                    System.out.println(rs.getString("username"));
//                    dv.setVisible(true); 
//                    txtusername.setText("");
//                    txtpassword.setText("");
//                    dispose();
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "COBA LAGIIIII !!!!");
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }     
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(periksa);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(230, 56, 62));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(179, 47, 51));
    }//GEN-LAST:event_buttonPeriksaMouseClicked

    private void buttonKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKasirMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(kasir);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(230, 56, 62));
        buttonObat.setBackground(new Color(179, 47, 51));
    }//GEN-LAST:event_buttonKasirMouseClicked

    private void buttonObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonObatMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(obat);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(230, 56, 62));
    }//GEN-LAST:event_buttonObatMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String sql = "Select * from pegawai where username = '" + mencoba + "'";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.Logon();
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                txtnamapekerja.setText(rs.getString("nama")); 
                id_pegawai = rs.getString("id_pegawai");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
        
        GregorianCalendar date = new GregorianCalendar();
            
        String tgl_now = String.valueOf(date.get(Calendar.DAY_OF_MONTH));
        String bulan_now = String.valueOf((date.get(Calendar.MONTH)+1)%12);
        String tahun_now = String.valueOf(date.get(Calendar.YEAR));
        rightnow = tahun_now+"-"+bulan_now+"-"+tgl_now;
        
    }//GEN-LAST:event_formWindowActivated

    private void buttonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk keluar sekarang?","Close Massage",JOptionPane.YES_NO_OPTION);
        if (confirm==0){
            MainView mv = new MainView();
            mv.setVisible(true); 
            dispose();
        }
    }//GEN-LAST:event_buttonLogoutMouseClicked

    private void prosesPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesPeriksaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk proses?","Proses",JOptionPane.YES_NO_OPTION);
        if (confirm==0){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
            String sql = "Select * from pasien where nama = '" + txtnamapasien.getText() + "' and alamat ='"+txtalamat.getText()+"' and tgl_lahir ='"+txttanggallahir.getText()+"'";
            ConnectionManager conMan = new ConnectionManager();
            Connection conn = conMan.Logon();
            String id_patiente = null;
            try {
                Statement stm = conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                if (rs.next()) {
                    id_patiente = rs.getString("id_pasien");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            Pemeriksaan pmr = new Pemeriksaan();
            pmr.setTgl_pemeriksaan(rightnow);
            pmr.setId_pegawai(id_pegawai);
            pmr.setId_pasien(id_patiente);
            
            Execute exe = new Execute();
            String id_periksa = exe.InsertPemeriksaan(pmr);
            System.out.println("ini id heyhey = "+id_periksa);
            
            // Proses Resep
            Resep rsp = new Resep();
            rsp.setId_pemeriksaan(id_periksa);
            String id_resp = exe.InsertResep(rsp);
            System.out.println("ini id resep10 = "+id_resp);
            
            // Proses List Obat
            Execute eks = new Execute();
            Resep_Item ri = new Resep_Item();
            String obat = null;
            String hasil = null;
            ri.setId_resep(id_resp);
            if (cbtramadol.isSelected()){
                obat = CekID_Obat(cbtramadol.getText());
                ri.setId_obat(obat);
                hasil = eks.InsertResep_Item(ri);
            }
            if (cbpenisilin.isSelected()){
                obat = CekID_Obat(cbpenisilin.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbasammefenamat.isSelected()){
                obat = CekID_Obat(cbasammefenamat.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbardium.isSelected()){
                obat = CekID_Obat(cbardium.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbbetadine.isSelected()){
                obat = CekID_Obat(cbbetadine.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbcetirizine.isSelected()){
                obat = CekID_Obat(cbcetirizine.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbdeksametason.isSelected()){
                obat = CekID_Obat(cbdeksametason.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbesperson.isSelected()){
                obat = CekID_Obat(cbesperson.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbrhinos.isSelected()){
                obat = CekID_Obat(cbrhinos.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            if (cbparacetamol.isSelected()){
                obat = CekID_Obat(cbparacetamol.getText());
                ri.setId_obat(obat);
                hasil = exe.InsertResep_Item(ri);
            }
            
            JOptionPane.showMessageDialog(null, "Sudah Terproses");
            displayAll();
            
            txtnamapasien.setText("");
            txtalamat.setText("");
            txttanggallahir.setText("");
        }
    }//GEN-LAST:event_prosesPeriksaActionPerformed

    private void tabellistpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellistpasienMouseClicked
        int row = tabellistpasien.getSelectedRow();
        txtnamapasien.setText(tabellistpasien.getValueAt(row, 0).toString());
        txtalamat.setText(tabellistpasien.getValueAt(row, 1).toString());
        txttanggallahir.setText(tabellistpasien.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tabellistpasienMouseClicked

    private void tabelpemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpemeriksaanMouseClicked
        int row = tabelpemeriksaan.getSelectedRow();
        id_resep = (tabelpemeriksaan.getValueAt(row, 0).toString());
        Adapter ag = new Adapter();
        Object[][]myrsp_item = ag.getResep_ListObat(id_resep);
        tabellistobat.setModel(new javax.swing.table.DefaultTableModel(
            myrsp_item,
            new String [] {
                "ID Resep", "ID Obat"
            }
        ));
        jScrollPane3.setViewportView(tabellistobat);
    }//GEN-LAST:event_tabelpemeriksaanMouseClicked

    private void tabellistobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellistobatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabellistobatMouseClicked

    private void bayarbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarbuttonMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk proses?","Proses",JOptionPane.YES_NO_OPTION);
        if (confirm==0){
            Execute exe = new Execute();
            Resep rsp = new Resep();
            String hasil = exe.UpdateStripBayar(rsp, id_resep);
            System.out.println(hasil);
            JOptionPane.showMessageDialog(null, "Sudah Terproses");
            displayAll();
        }
    }//GEN-LAST:event_bayarbuttonMouseClicked

    private void tabelpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpembayaranMouseClicked
        int row = tabelpembayaran.getSelectedRow();
        idresephasil.setText((tabelpembayaran.getValueAt(row, 0).toString()));
        id_resep = idresephasil.getText();
        idpemeriksaanhasil.setText((tabelpembayaran.getValueAt(row, 1).toString()));
        System.out.println(rightnow);
        tanggalhasil.setText(rightnow);
        String query = "SELECT pemeriksaan.id_pemeriksaan,pasien.nama,pasien.tgl_lahir FROM pemeriksaan LEFT JOIN pasien ON pemeriksaan.id_pasien = pasien.id_pasien WHERE pemeriksaan.id_pemeriksaan ="+(tabelpembayaran.getValueAt(row, 1).toString())+"";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.Logon();
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            if (rs.next()){ 
                namapasienhasil.setText(rs.getString("nama"));
                tanggallahirhasil.setText(rs.getString("tgl_lahir"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
        query = "SELECT nama FROM pemeriksaan LEFT JOIN pegawai ON pemeriksaan.id_pegawai = pegawai.id_pegawai WHERE pemeriksaan.id_pemeriksaan ="+(tabelpembayaran.getValueAt(row, 1).toString())+"";
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            if (rs.next()){ 
                namadokterhasil.setText(rs.getString("nama"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
        
        Adapter ag = new Adapter();
        Object[][]myobat = ag.getListObat(idresephasil.getText());
        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            myobat,
            new String [] {
                "ID Obat", "Nama Obat", "Harga"
            }
        ));
        jScrollPane5.setViewportView(tabelobat);
        
        int simpan = 0;
        int jumlahrow = (tabelobat.getRowCount());
        for (int i=0;i<jumlahrow;i++){
            simpan = simpan + Integer.valueOf(tabelobat.getValueAt(i, 2).toString());
            System.out.println("ini hasil simpan yang ke-"+i+" dan ini jumlah simpan ="+simpan);
        }
        totalhasil.setText(String.valueOf(simpan));
       
    }//GEN-LAST:event_tabelpembayaranMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk print struk?","Print",JOptionPane.YES_NO_OPTION);
        if (confirm==0){
            Execute exe = new Execute();
            Resep rsp = new Resep();
            String hasil = exe.UpdateBelumBayar(rsp, id_resep);
            System.out.println(hasil);
            JOptionPane.showMessageDialog(null, "Sudah Terproses");
            displayAll();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterView().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JButton bayarbutton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel buttonHome;
    private javax.swing.JPanel buttonKasir;
    private javax.swing.JPanel buttonLogout;
    private javax.swing.JPanel buttonObat;
    private javax.swing.JPanel buttonPeriksa;
    private javax.swing.JCheckBox cbardium;
    private javax.swing.JCheckBox cbasammefenamat;
    private javax.swing.JCheckBox cbbetadine;
    private javax.swing.JCheckBox cbcetirizine;
    private javax.swing.JCheckBox cbdeksametason;
    private javax.swing.JCheckBox cbesperson;
    private javax.swing.JCheckBox cbparacetamol;
    private javax.swing.JCheckBox cbpenisilin;
    private javax.swing.JCheckBox cbrhinos;
    private javax.swing.JCheckBox cbtramadol;
    private javax.swing.JPanel denied;
    private javax.swing.JPanel home;
    private javax.swing.JTextField idpemeriksaanhasil;
    private javax.swing.JTextField idresephasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel kasir;
    private javax.swing.JLabel labelboong2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField namadokterhasil;
    private javax.swing.JTextField namapasienhasil;
    private javax.swing.JPanel obat;
    private javax.swing.JPanel penyakit;
    private javax.swing.JPanel periksa;
    private javax.swing.JButton prosesPeriksa;
    private javax.swing.JTable tabellistobat;
    private javax.swing.JTable tabellistpasien;
    private javax.swing.JTable tabelobat;
    private javax.swing.JTable tabelpembayaran;
    private javax.swing.JTable tabelpemeriksaan;
    private javax.swing.JTextField tanggalhasil;
    private javax.swing.JTextField tanggallahirhasil;
    private javax.swing.JTextField totalhasil;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JLabel txtnamapekerja;
    private javax.swing.JTextField txttanggallahir;
    // End of variables declaration//GEN-END:variables
}
